version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana-oss:latest # Use the open-source version
    container_name: grafana
    restart: always
    ports:
      - '3000:3000' # Expose Grafana on host port 3001 (to avoid conflict if app uses 3000)
    volumes:
      - grafana-storage:/var/lib/grafana # Persist Grafana data
      - ./grafana/provisioning:/etc/grafana/provisioning # Mount provisioning files
    depends_on:
      - prometheus
    environment:
      # Optional: Pre-configure Prometheus datasource (adjust URL if needed)
      # GF_DATASOURCES_0_NAME: Prometheus
      # GF_DATASOURCES_0_TYPE: prometheus
      # GF_DATASOURCES_0_URL: http://prometheus:9090
      # GF_DATASOURCES_0_ACCESS: proxy
      # GF_DATASOURCES_0_IS_DEFAULT: true
      # GF_SECURITY_ADMIN_USER: admin # Default user
      # GF_SECURITY_ADMIN_PASSWORD: admin # Default password (CHANGE THIS IN PRODUCTION)
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

volumes:
  grafana-storage: {} # Define the volume for Grafana data